Flatpak: update dbus-python version so it builds again
Looks like the recent update to python 3.8 has caused it to stop
compilling

```
   /usr/lib/gcc/x86_64-unknown-linux-gnu/10.1.0/../../../../x86_64-unknown-linux-gnu/bin/ld: test/test_test_import_repeatedly-import-repeatedly.o: in function `main':
  /tmp/pip-install-opubo76x/dbus-python/test/import-repeatedly.c:10: undefined reference to `Py_Initialize'
  /usr/lib/gcc/x86_64-unknown-linux-gnu/10.1.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /tmp/pip-install-opubo76x/dbus-python/test/import-repeatedly.c:11: undefined reference to `PyRun_SimpleStringFlags'
  /usr/lib/gcc/x86_64-unknown-linux-gnu/10.1.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /tmp/pip-install-opubo76x/dbus-python/test/import-repeatedly.c:12: undefined reference to `Py_Finalize'
  collect2: error: ld returned 1 exit status
  make[1]: *** [Makefile:1261: test/test-import-repeatedly] Error 1
  make[1]: Leaving directory '/tmp/pip-install-opubo76x/dbus-python/build/temp.linux-x86_64-3.8'
  make: *** [Makefile:971: all] Error 2
  make: Leaving directory '/tmp/pip-install-opubo76x/dbus-python/build/temp.linux-x86_64-3.8'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-opubo76x/dbus-python/setup.py", line 83, in <module>
      setup(
    File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-opubo76x/dbus-python/setup.py", line 67, in run
      subprocess.check_call(['make', '-C', builddir] + make_args)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', '-C', '/tmp/pip-install-opubo76x/dbus-python/build/temp.linux-x86_64-3.8', 'pythondir=/tmp/pip-install-opubo76x/dbus-python/build/lib.linux-x86_64-3.8', 'pyexecdir=/tmp/pip-install-opubo76x/dbus-python/build/lib.linux-x86_64-3.8']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for dbus-python
```