backend: Disable vaapi at the root
Changes in gst-vaapi, vaapi, and the vaapi driver, combined with
clutter-gst's bad integration with those means that things regularly
break, and totem isn't able to display anything properly.

Until we switch the display sink away from clutter-gst and clutter-gtk
we need to disable vaapi to get anything on screen.

Fixes:
Shader compilation failed:
0:91(21): warning: `cogl_layer0' used uninitialized
0:104(21): warning: `cogl_layer1' used uninitialized
0:117(21): warning: `cogl_layer2' used uninitialized
0:128(16): error: no function with name 'clutter_gst_sample_video3'
Failed to link GLSL program:
error: linking with uncompiled/unspecialized shader